CREATE TABLE IF NOT EXISTS dataset_sources (
    source_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name TEXT NOT NULL UNIQUE,
    source_path TEXT,
    imported_at TEXT NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS uploads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    filename TEXT NOT NULL,
    rows_processed INTEGER NOT NULL,
    products_added INTEGER NOT NULL,
    reviews_added INTEGER NOT NULL,
    duplicates_skipped INTEGER NOT NULL,
    uploaded_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    product_id TEXT PRIMARY KEY,
    product_name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Uncategorized',
    clean_price DOUBLE PRECISION,
    source_id INTEGER REFERENCES dataset_sources(source_id),
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews (
    review_id TEXT PRIMARY KEY,
    product_id TEXT NOT NULL REFERENCES products(product_id),
    rating DOUBLE PRECISION,
    full_review TEXT,
    cleaned_review TEXT NOT NULL,
    sentiment TEXT,
    source_id INTEGER REFERENCES dataset_sources(source_id),
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_products_normalized_name
ON products(normalized_name);

CREATE INDEX IF NOT EXISTS idx_products_category
ON products(category);

CREATE INDEX IF NOT EXISTS idx_reviews_product_id
ON reviews(product_id);

CREATE INDEX IF NOT EXISTS idx_reviews_sentiment
ON reviews(sentiment);

CREATE INDEX IF NOT EXISTS idx_reviews_rating
ON reviews(rating);

CREATE INDEX IF NOT EXISTS idx_reviews_source_id
ON reviews(source_id);
